### PR TITLE
Use Homebrew's libantlr3

### PR DESCRIPTION
**Pull request by pathawks**
Homebrew already has a formula for [`libantlr3c`](https://github.com/Homebrew/homebrew-core/blob/e9cc380ef95a17b8c26b4881684208004c3695fa/Formula/libantlr3c.rb). It is possible to use an already installed version instead of downloading it again.

### CODE REVIEW

**Comment by pathawks** [comment]
Travis is currently failing because of #11

**Comment by 4tXJ7f** [comment]
Is `libantlr3c` including the antlr binary? Previously, we were depending on `libantlr3c` and `antlr@3` but then `antlr@3` was removed from homebrew. Because our scripts for getting antlr download the binary and the libraries, I removed both dependencies.

**Comment by pathawks** [comment]
You are right, `libantlr3c` does not include the binaries.

I see that `antler@3` was removed in https://github.com/Homebrew/homebrew-core/pull/23083. I wonder if this repo could provide [that formula](https://github.com/Homebrew/homebrew-core/blob/2a9c5977a3a6361c6b144df2f5352bbf93281ae6/Formula/antlr%403.rb) in the same way it provides [`swig@2`](https://github.com/CVC4/homebrew-cvc4/blob/master/Formula/swig%402.rb)?

One problem with the current approach is that ANTLR is downloaded and compiled even if it might already be installed. This means that upgrading to a future version of CVC4 would again require downloading and building the (presumably) same version of ANTLR.

**Comment by 4tXJ7f** [comment]
Yes, I think that that would be a decent solution. Can you update the PR to include `antlr@3`?

**Comment by pathawks** [comment]
Sorry it has taken me so long, but I have tried to update this PR to depend on `libantlr3c` and `antlr@3` using the same version of **antlr** that CVC4 expects.

**Pull request closed without merging**
