### PR TITLE
Always install TOML

### PR DESCRIPTION
**Pull request by pathawks**
This PR attempts to fix the problem I encountered with #40 where TOML needed to be manually installed system-wide.

### CODE REVIEW

**Comment by pathawks** [comment]
Apparently it didn't work for `--HEAD` 🤷🏼‍♂️

**Comment by 4tXJ7f** [comment]
Thanks a lot for the PRs. Yeah... I've also been fighting with the toml issue quite a bit unfortunately. I will take another look.

**Comment by pathawks** [comment]
The problem seems to be that CMake is finding the system Python rather than the virtual environment Python, so TOML must be installed system-wide for CMake to find it, I guess.

**Comment by 4tXJ7f** [comment]
> The problem seems to be that CMake is finding the system Python rather than the virtual environment Python

Yes, that was my diagnosis as well (see my various attempts [here](https://github.com/CVC4/homebrew-cvc4/pull/35)).

> so TOML must be installed system-wide for CMake to find it, I guess.

Unfortunately, I don't think that that's an acceptable solution because the long-term plan is to submit CVC4 to the official Homebrew repository. A possible solution is a configuration flag for CVC4 that allows the user (in this case the Homebrew formula) to specify the path of the Python executable, which works (I've tested it) but is quite ugly. I'll need to tinker with this some more.

**Comment by 4tXJ7f** [comment]
I have implemented a solution that seems to work for now, so I am closing this PR.

**Pull request closed without merging**
